USE dbDailyHelper;

CREATE TABLE tbUser(
Id UNIQUEIDENTIFIER PRIMARY KEY,
Email VARCHAR(45) UNIQUE NOT NULL,
Pass VARCHAR(45) NOT NULL);

CREATE TABLE tbTodo(
Id UNIQUEIDENTIFIER PRIMARY KEY,
TodoText VARCHAR(45) NOT NULL,
IdUser UNIQUEIDENTIFIER NOT NULL,
FOREIGN KEY(IdUser) REFERENCES tbUser(Id));

CREATE TABLE tbNote(
Id UNIQUEIDENTIFIER PRIMARY KEY,
NoteText VARCHAR(45) NOT NULL,
IdUser UNIQUEIDENTIFIER NOT NULL,
FOREIGN KEY(IdUser) REFERENCES tbUser(Id));

CREATE TABLE tbAccount(
Id UNIQUEIDENTIFIER PRIMARY KEY,
Account VARCHAR(45) UNIQUE NOT NULL);

CREATE TABLE tbAccountInfo(
Id UNIQUEIDENTIFIER PRIMARY KEY,
IdUser UNIQUEIDENTIFIER NOT NULL,
FOREIGN KEY(IdUser) REFERENCES tbUser(Id),
IdAccount UNIQUEIDENTIFIER NOT NULL,
FOREIGN KEY(IdAccount) REFERENCES tbAccount(Id),
AccountLogin VARCHAR(45) NOT NULL,
AccountPass VARCHAR(45) NOT NULL,
IsActive BIT NOT NULL);

INSERT INTO tbAccount(Id, Account)
VALUES (NEWID(), 'VK'), (NEWID(), 'Twitter'), (NEWID(), 'Facebook');